worker_processes 1;
daemon off;

error_log stderr;

events {
  worker_connections 1024;
}

http {
  charset utf-8;
  access_log /dev/stdout;
  default_type application/octet-stream;
  include mime.types;

  server {
    listen 8080;
    root public;

    location /health {
      default_type application/json;
      try_files /health =404;
    }
  }
}
